apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sms-gateway
  name: sms-gateway
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30080
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: https
    nodePort: 30043
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    io.kompose.service: sms-gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
